---
title: "University of Pennsylvania - Fall 2024"
editor:
  render-on-save: true
---

Inspired by the The University of Pennsylvania's [Intro to Python practice exam](https://www.cis.upenn.edu/~cis110/current/py/assets/exams/exam1/fa24_practice.pdf), I added the questions relevant to our course :)

## Question 1 - List Math 🧮

What will print?

```py
x = [1, 2, 3]
x[len(x) - 1] = x[len(x) - x[0]] - x[1]
print(x[2])
```

<details>
  <summary>👀 Hint</summary>
  <p>Try drawing out what happens @ each index</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <p>1</p>
</details>

## Question 2 - Lists & Loops 🔁

What will print?

```py
numbers = [4, 2, -1]
x = 1
for num in numbers:
    x = x * numbers
print(x)
```

<details>
  <summary>👀 Hint</summary>
  <p>Notice any syntax problems?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <p>nothing shall print cause there's a problem! U can't multiple a number by a list</p>
</details>

## Question 3 - Tracing Functions 🔍

Here's a python file that features a few cool functions.

```py
def func_three(x, y):
    print(f"func_three arguments: x={x}, y={y}")
    result1 = x * 3
    result2 = y * 2
    final_result = result1 + result2
    print(f"func_three returning: {final_result}")
    return final_result

def func_two(num):
    print("func_two argument: num=" + str(num))
    result = num * 2
    print("funct_two returning: " + str(result))
    return result

def func_one(a, b):
    print(f"func_one arguments: a={a}, b={b}")
    result1 = a + b
    result2 = func_two(result1)
    result3 = func_three(a, b)
    final_result = result2 - result3
    print(f"func_one returning: {final_result}")
    return final_result

print("Starting main program")
x = 10
y = 5
z = func_one(y, x)
print("The final result is: " + str(z))
```

When the program is run, eight lines are printed. For each of the following lines, fill in the blanks to show what values the variables have when they are printed out. Also, mark the order in which they are printed in the “Order” column starting at 1. The order for the first line is marked for you.

| Printed Line                                           | Order |
| ------------------------------------------------------ | ----- |
| Starting main program                                  | 1     |
| The final result is: **\_\_\_\_**                      |       |
| `func_one` arguments: a=**\_\_\_\_** , b=**\_\_\_\_**  |       |
| `func_one` returning: **\_\_\_\_**                     |       |
| `func_two` argument: num=**\_\_\_\_**                  |       |
| `func_two` returning: **\_\_\_\_**                     |       |
| `func_three` argument: x=**\_\_\_\_** , y=**\_\_\_\_** |       |
| `func_three` returning: **\_\_\_\_**                   |       |

<details>
  <summary>👀 Hint</summary>
  <p>Add arrows to link from where the function is being called to the function definition. This will make it easier to follow the order of execution :^)</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    Starting main program
    func_one arguments: a=5, b=10
    func_two argument: num=15
    funct_two returning: 30
    func_three arguments: x=5, y=10
    func_three returning: 35
    func_one returning: -5
    The final result is: -5
    </code></pre>
</details>

## Question 4 - Time is Ticking ⏰

The following program is supposed to print out a time readout every fifteen minutes over the course of one day, starting with 12:00 AM, then 12:15 AM, then 12:30 AM and so on. Times in the second half of the day should be printed using the 12-hour clock, meaning that the full set of printed times should include 96 timestamps and should match the format & pattern shown in the following example:

```text
12:00 AM
12:15 AM
12:30 AM
12:45 AM
1:00 AM
... // ellipses are not printed literally lol
11:30 AM
11:45 AM
12:00 PM
12:15 PM
...
11:45 AM
```

Help write this clock program by filling in the blanks

```py
for hour in range(24):
    for minute in range(0, 60, _BLANK_0_):
        if _BLANK_2_ or hour == 12:
            hour_to_print = "12"
        else:
            hour_to_print = str(hour % _BLANK_3_)
        if minute == 0:
            minute_to_print = ":00"
        else:
            minute_to_print = ":" + str(minute)
        if _BLANK_4_:
            suffix = "AM"
        else:
            suffix = "PM"
        print(hour_to_print + minute_to_print + " " + suffix)
```

<details>
  <summary>👀 Hint</summary>
  <p>You can control how a loop increments by using a step. For example, range(0, 60) starts at 0, goes up to but does not include 60, and increases by 1 each time, while range(0, 60, 30) starts at 0, goes up to but does not include 60, and increases by 30 each time. If time is going up by 15 minutes, whats our "step"?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    for hour in range(24):
        for minute in range(0, 60, 15):
            if hour % 12 == 0 or hour == 12:
                hour_to_print = "12"
            else:
                hour_to_print = str(hour % 12)
            if minute == 0:
                minute_to_print = ":00"
            else:
                minute_to_print = ":" + str(minute)
            if hour < 12:
                suffix = "AM"
            else:
                suffix = "PM"
            print(hour_to_print + minute_to_print + " " + suffix)
  </code></pre>
</details>
