---
title: "🎯 Practice Midterm - Fall 2025"
editor:
  render-on-save: true
---

## Question 1 - Fix the Code

Find and correct the mistakes.

```python
42isACoolNumber = 42
a cool book = "Hitchhiker's Guide to the Galaxy";
favorite#color = "green"
```

<details>
  <summary>👀 Hint</summary>
  <p>What can variables not contain?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    a_cool_number = 42
    a_cool_book = "Hitchhiker's Guide to the Galaxy"
    favorite_color = "green"
  </code></pre>
</details>

## Question 2 - Tracing

Given the Python code below, if a user inputs 12, fill in all the blanks. If the math feels spooky, feel free to grab a (non-programmable) calculator!!

```python
# initialize defaults
total = 4

# user inputs 12
num = int(input("What's a cool number?"))

# do math
num += 2 # the num's value is now _______
num += 4 # the num's value is now _______
num += 6 # the num's value is now _______
total += num % 6

# output result
print(total) # the printed total is ________
```

<details>
  <summary>👀 Hint</summary>
  <p>num is being updated step-by-step. For num % 6, what is the remainder when dividing by 6?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    # initialize defaults
    total = 4

    # user inputs 12
    num = int(input("What's a cool number?"))

    # do math
    num += 2 # the num's value is now 14
    num += 4 # the num's value is now 18
    num += 6 # the num's value is now 24
    total += num % 6

    # output result
    print(total) # the printed total is 4

</code></pre>

</details>

## Question 3 - Evens 🧮

Write a Python function that prints all the even numbers from 1 to 10 (inclusive). Full marks are awarded for the most logically sound program that adheres to best-practices.

<details>
  <summary>👀 Hint</summary>
  <p>What operators come to mind when trying to figure out when trying to see if a number is divisible by 2?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    def print_even_numbers():
        for num in range(1, 11):
            if num % 2 == 0:
                print(num)
  </code></pre>
</details>

## Question 4 - Study Tracker ⏰

Your parents are on your case because they think that you are not spending enough time studying. You of course deny this. Since your parents don't believe you, you make an agreement with them where they can track the number of hours that you are home studying at your desk over the course of a week.

Create a Python program that:

- Calculates the total hours studied over a period of 1 week, using this sample data: `2.1, 1.0, 0.74, 3.2, 2.2, 4.0, 0.15`
- Displays the total amount studied, formatted to two decimal places
- Full marks are awarded for the most logically sound program that adheres to best practices 🧑‍🎓✨

<details>
  <summary>👀 Hint</summary>
  <p>A loop is easier to maintain than seven separate variables 👀</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <p>You might have been tempted to store everything in a variable for this problem. If your gut tells you, "Hmm, something feels off, maybe this is inefficient," trust that instinct!!</p>
  <pre> <code class="language-python">
    total_hours = 0
    for hour in [2.1, 1.0, 0.74, 3.2, 2.2, 4.0, 0.15]:
        total_hours += hour
    print(f"{total_hours} hours have been studied")
  </code></pre>
</details>

## Question 5 - Padding the Bill ﹩

We want to find out the farmer’s raw cost before markups.

_Definitions:_

- x: the raw cost for creating the product
- G: grocery cost after grower markup
- T: transportation cost (flat rate)
- S: final selling price (what you pay)

_Equations:_

Grocery Cost with grower markup:

$$
G = \tfrac{5}{4}x
$$

Final selling price with store markup and transportation:

$$
S = 1.20G + T
$$

If your grocery bill is $400 and transportation is $12.99, write a Python function that takes your grocery bill as input and returns the farmer’s raw cost (`x`).

<details>
  <summary>👀 Hint</summary>
  <p>Try working thru the problem backwards 👀</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
  
    # something like this
    def farmer_raw_cost(selling_price: float):
        grower_markup_rate = 5 / 4
        store_markup_rate = 1.20
        transportation_rate = 12.99
        before_store_cost = (selling_price - transportation) / store_markup_rate
        before_grower_cost = before_store_cost / grower_markup_rate
        return before_grower_cost
  </code></pre>
</details>

## Question 6 - Los Pollos Hermanos 🐓👒

Your distant relative makes delicious burritos, and you believe they should start selling them. They've come up with the following pricing model:

- The first two burritos are $12 each
- Any additional burritos are $6 each

Create a Python program that:

- Stores the number of burritos in a variable (this value may change)
- Calculates the total cost for this order, formatted to two decimal places
- Full marks are awarded for the most logically sound program that adheres to best-practices

<details>
  <summary>👀 Hint</summary>
  <p>Use conditionals 👀</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    desired_burritos = 42 # many burritos
    standard_price = 12
    bulk_price = 6
    total_burrito_cost = 0

    if desired_burritos <= 0:
        total_burrito_cost = 0 # can't charge negative money lol
    if 0 < desired_burritos <= 2:
        total_burrito_cost = desired_burritos * standard_price
    if 0 < desired_burritos > 2:
        first_two_cost = 2 * standard_price
        additional_cost = (desired_burritos - 2) * bulk_price
        total_burrito_cost = first_two_cost + additional_cost

    print(f"That will be ${total_burrito_cost:.2f} for your 100% legal burritos")

</code></pre>

</details>
