---
title: "✍️ For Loops"
editor:
  render-on-save: true
---

## Level 1

### Ranges

#### Print "hello" 5 times using a `for-loop`

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
how do you create ranges?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
    for i in range(5):
        print("hello")
```
:::

#### Print the values from 1 to 10.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
How can you define the start and end of a range?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
    for i in range(1, 11):
        print(i)
```
:::

#### Print every 3rd number from 1 to 10.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
How can you define the start and end of a range?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
    for i in range(1, 11, 3):
        print(i)
```
:::

#### Print every number from 10 down to 1 (inclusive).

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Did anyone say that you can't use a negative number for the step/increment?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
    for i in range(10, 0, -1):  # start at 10, stop before 0, change by -1 each turn
        print(i)
```
:::

### Tracing Loops

What will be the output of this program?

```python
grade = 78
for _ in range(10):
	grade += 1

print(grade)
```

> Note: it's actually legal to name a variable as just an underscore _ like this and the convention is that we do this when we have to create a variable but we have no intention of actually *using* the variable.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
What happens when I add 1 to a grade 10 times?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```text
88
```
:::

### Tracing MORE Loops

What will be the output of this program:

```python
number = 3
value = 0
for i in range(4):
    value += number

print(value)
```

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
What happens when I add 3 to a value 4 times?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```text
12
```
:::



### Countdown (aborted)

Write a countdown timer using range(10, 0, -1) that counts down from 10 to 1. However, when the count hits 3, print "Emergency stop triggered!" and exit the loop immediately using `break`.


```{pyodide}


```


:::{.callout-tip title="Solution 1" collapse="true"}
```{pyodide}
for count in range(10, 0, -1):
    if (count == 3):
        print("Emergency stop triggered!")
        break
    # why don't we need to write "else:" here?

    print(count)

print("Phew, that was close!")
```
:::


## Level 2

### You got the Power

Write a program that **prints** the powers of 2 from 2⁰ to 2¹⁵. Each line should display the exponent and the corresponding power of 2 in the format:

```text
2 to the power of 0 is 1
2 to the power of 1 is 2
...
2 to the power of 15 is 32768
```

```{pyodide}
# add your code here

```


:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Think about starting with the smallest power, 2⁰, and repeatedly multiplying by 2. The base case is the first power, 2⁰ = 1.
:::
:::

:::{.callout-tip title="Solution 1" collapse="true"}
```{pyodide}
power = 1
for expo in range(16):
    print(f"2 to the power of {expo} is {power}")
    power *= 2
```
:::


:::{.callout-tip title="Solution 2" collapse="true"}
```{pyodide}
for expo in range(16):
    print(f"2 to the power of {expo} is {2**expo}")
```
:::

### That's odd

Print only odd numbers up to 100

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
<b>A number is even if is divisible by 2</b> and to check divisibility, you can use an operator that gives the remainder of a division. Which operator in Python tells you the remainder when dividing by 2?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
for i in range(1, 101):
    if i % 2 != 0:
        print(i)
```
:::

### Don't Panic

Print only even numbers up to 100. If the number is divisible by 42, print "DON'T PANIC" instead of the number.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
How do you check if a number is even? Apply the same idea to test divisibility by 42 👀
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
for i in range(100):
    if i % 42 == 0 and i != 0:
        print("DON’T PANIC")
    if i % 42 != 0 and i % 2 == 0:
        print(f"{i} is even")
```
:::

### Break-out!

Print numbers between 7 and 100 but stop as soon as you find a number that is divisble by 6.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Take a break with your rarely used operator modulus (%)
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
for num in range(7, 100):
    if num % 6 == 0:
        print(f"{num} is divisible by 6. Stopping.")
        break

print(num)
```
:::

### Factorial

Calculate the factorial of a number `num`:
```{pyodide}
num = 

```

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
The factorial of 3 is: 1 x 2 x 3
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
num = 8
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

print(f"The factorial of {num} is: {factorial}")
```
:::



### JAC
Write a program that prints each character (i.e. each letter) of the string "John Abbott College" on a new line. However, if the character is a vowel (a, e, i, o, u), skip it using `continue`.

```{pyodide}
jac = "John Abbott College"

# add your code here

```


:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Remember that a for loop can go through the individual characters of a string (refer back to the for-loop page if needed.)
:::
:::

:::{.callout-tip title="Solution 1" collapse="true"}
```{pyodide}
jac = "John Abbott College"

for letter in jac:
    if (
        letter == 'a'
        or letter == 'A'
        or letter == 'e'
        or letter == 'E'
        or letter == 'i'
        or letter == 'I'
        or letter == 'o'
        or letter == 'O'
        or letter == 'u'
        or letter == 'U'
    ):
        continue

    print(letter)   # why don't we need "else:" before this line?
```
:::


:::{.callout-tip title="Solution 2" collapse="true"}
We can make the code much shorter by using `in` to test whether the letter we are considering is present anywhere in a given string:  
```{pyodide}
jac = "John Abbott College"

for letter in jac:
    if letter in "aAeEiIoOuU":
        continue

    print(letter)   # why don't we need "else:" before this line?
```
:::

### sdrawkcaB

Ask the user to enter some text, then print it backwards (using a loop). In Thonny, start with:
```python
something: str = input("Type something here: ")
```
> **Note:** the `input` function won't work in this webpage, so either use Thonny for this, or instead of using `input` you can just assign some string value.

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Adding isn't just for numbers!
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
something: str = "eybdoog"
backwards: str = ""         # start with an empty string

for letter in something:
    backwards = letter + backwards

print(f"You say '{something}', I say '{backwards}'")
```
:::

### 46?

Ask yourself what the 2 outputs of this program should be and then try it out and make sure you understand what the code is doing!
```{pyodide}
x = 0

for i in "four":
    x = x + 1
print(x)

# reset back to zero:
x = 0

for i in "six":
    x = x + 1
print(x)
```

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
What value(s) will the loop variable i be assigned as the loops repeat?
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```text
4
3

Each of these loops is iterating across the sequence of characters (e.g. letters) in a string, so a string of length 4 (meaning 4 characters long like "abcd" or "desk" or "four"...) will loop 4 times. This code is essentially counting how many characters are in a string and then printing the result.
```
:::

### Clock

Display every minute of every hour in a day like:  
0:00  
0:01  
0:02  
...  
23:58  
23:59  

:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
Save yourself a lot of typing by using 2 loops!
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
for hour in range(0, 24):
    for minute in range(0, 60):
        print(f"{hour:02}:{minute:02}") # the :02 formatting option will print the number using 2 digits and will add a zero on the left if needed.
```
:::


### Continue breaking
Write a program using range(1, 51) that prints numbers from 1 to 50, but with two rules:
1. Use continue to skip any number that is a multiple of 3.  
2. Use break to stop the loop completely as soon as the sum of the *non multiple of three* numbers seen reaches or exceeds 40.

```{pyodide}
# add your code here

```


:::{.callout-hint}
:::{.callout-note title="Hint" collapse="true"}
As part of this, you need to accumulate a *total* based on the numbers that are *not* multiples of 3.
:::
:::

:::{.callout-tip title="Solution" collapse="true"}
```{pyodide}
total = 0

for i in range(1, 51):
    if (i % 3 == 0):    # skip multiples of three
        continue

    total = total + i   # update our total amount

    if (total >= 40):   # check the new total
        break

print(f"The final total is {total}")        
```
:::
