---
title: "Youmna"
---
This syllabus applies only to Youmna's sections. 

# Office Hours
I am free Mondays from 1:00-2:30pm and Tuesdays 10:00 am - 12:30 pm. For other availabilities, [download](door_schedule.pdf){target="_blank"} my door schedule

You can send me a MIO if you need help or pass by my office (P-311).

# Work Submission

My assignments and labs are always posted on Omnivox but submiited via [Gradescope.ca](https://www.gradescope.ca/courses/39225)

- Login with your student id email: `123456@johnabbott.qc.ca`
- You might need to set the password if logging-in for the first time. 

# Every week

:::{.callout-note icon="false" collapse="true" title="📚 Before class - Preparation ~ 1 hour"}

**Goal: Arrive prepared to learn and practice.**

* Read the notes of this week's topic and go over the examples
* Complete the **Test Myself** questions.
* Try the practice problems on your own.
* Prepare as if you will have a **short paper quiz** on a weekly basis. 

:::



:::{.callout-tip icon="false" collapse="true"  title="💻 In class - 3 hours"}

**Goal: Practice, apply, and deepen your understanding.**

* Ask questions and clarification on the content
  * Sometimes a recap or demo will be done by the teacher 
* ✏️ Complete a short **paper quiz/check** on the preparation material.
* Work through guided programming exercises or evaluated labs at your own pace or in groups of 2.
* Finish with a recap to check your understanding.

:::




::: {.callout-important icon="false" collapse="true"  title= "🚀 After class - Homework ~2 hours"}

**Goal: Consolidate your learning and stay on pace.**	

* You must complete the Lab/Assignment started in class
* Review anything from today's class that you found difficult.
* Then, prepare for the upcoming week.

:::
---

# Week 1

## 📚 Prep 

* Nothing to prepare for just be there on time.

## 💻 In class

* Introductions 
* Syllabus
* Files and folders
    * Python files
* Logging into One Drive to synchronize your files
* Lab 0 (0%)

## 🚀 After class

* Go over the notes for this week: [Files and folders](https://john-abbott-college.github.io/SN1-Notes/topics/03_introduction/01_file_manipulation/01_file_manipulation.html){target="_blank"}
* Setup your home computer:
  * [Setup Thonny](https://john-abbott-college.github.io/SN1-Notes/topics/02_getting_started/07_thonny/thonny.html) 

# Week 2

## 📚 Prep 

* Go over the notes and examples:
  * [Variables & Constants](https://john-abbott-college.github.io/SN1-Notes/topics/04_variables/02_variables/02_variables.html){target="_blank"}
  * [Integers & Floats](https://john-abbott-college.github.io/SN1-Notes/topics/04_variables/03_integers_floats/03_integers_floats.html){target="_blank"}
  * [Booleans](https://john-abbott-college.github.io/SN1-Notes/topics/04_variables/04_booleans/04_booleans.html){target="_blank"}
  * [Strings](https://john-abbott-college.github.io/SN1-Notes/topics/04_variables/05_strings/05_strings.html){target="_blank"}

## 💻 In class
- What is programming? Code your teacher activity.
- In-class Demo on Thonny
- ✏️ **Quiz 1 (1%)**:  Short paper quiz on Variables & Data Types
- Quiz recap
- Assignment 1 - Part 1 

## 🚀 After class

- Complete the practice exercises for that section

# Week 3

## 📚 Prep 

* Go over the notes:
  * [f-strings](https://john-abbott-college.github.io/SN1-Notes/topics/05_string_formatting/01_f_strings/01_f_strings.html){target="_blank"}
  * [Arithmetic operators](https://john-abbott-college.github.io/SN1-Notes/topics/06_operators/01_arithmetic_operators/01_arithmetic_operators.html){target="_blank"}
  * Try the [Practice](https://john-abbott-college.github.io/SN1-Notes/topics/06_operators/exercises/arithmetic_operators/arithmetic_operators.html){target="_blank"} problems

## 💻 In class

- Clarifications on Assignment 1 - Part 1 (why some gradescope tests failed)
- Short demo on f-strings and arithmetic operators
- The `math` module
- Clarifications on the modulo operator
- Practice Problems on the Modulo and Floor division
- Assignment 1 - Part 2 (**submitted in class**)

## 🚀 After class

- Complete the practice problems on assignment operators.
- Prepare for next class.



# Week 4

## 📚 Prep 

* Go over the notes:
  * [Assignment operators](https://john-abbott-college.github.io/SN1-Notes/topics/06_operators/02_assignment_operator/02_assignment_operator.html){target="_blank"}
  * Try the [Practice](https://john-abbott-college.github.io/SN1-Notes/topics/06_operators/exercises/assignment_operators/assignment_operators.html){target="_blank"} problems
  * [Conditional Statements](https://john-abbott-college.github.io/SN1-Notes/topics/07_conditionals/01_if_statements/01_if_statements.html){target="_blank"} 
  * [Comparison operators](https://john-abbott-college.github.io/SN1-Notes/topics/06_operators/03_comparison_operators/03_comparison_operators.html){target="_blank"}
  * Try the Practice problems (coming soon)



## 💻 In class

- Short demo on assignment operators
- Practice exercise on conditional statements 

- ✏️ **Quiz 2 (1%)**: Assignments operators and `if` statements
- Quiz recap
- Using other math functions from the `math` module.
- Assignment 1 - Part 3 (final part)



## 🚀 After class

- Complete the assignement at home 
- Prepare for next class



# Week 5

## 📚 Prep 

- Go over the notes:
  - Turtle Graphics (notes coming soon)
  - Custom Functions (notes coming soon)
  - For loops - introduction (notes coming soon)



## 💻 In class

- Drawing shapes with turtle graphics
- Introduction to **function parameters**
- Exercise on identifying parameters of a shape and re-draw it in multiple variations.
- Assignment 2 - Part 1 (submitted in class)



## 🚀 After class

- Prepare for next class

 

# Week 6

## 📚 Prep 

- Go over the notes:
  - Conditional `if/else` (notes coming soon)
  - Custom Functions (notes coming soon)
  - Function scopes (notes coming soon)
  - Try the practice questions (coming soon)



## 💻 In class

- Recap on functions :
  - Parameters
  - Return
  - Scope
- **Quiz 3** (1%): Functions 
- Functions with conditonals statements
- Assignment 2 - Part 2 (completing the functions in class - this is auto-graded)

## 🚀 After class

- Prepare for next class



# Week 6

## 📚 Prep 

Go over:

- The instructions of **Assignment 2 - Part 3** 

## 💻 In class

- Short Demo on drawing complex shapes with loops

- **Quiz 4** (1%): Functions (again- but harder)
- **In teams of 2:** Complete the Assignment 2 - Part 3 (demo in class)

## 🚀 After class

- Prepare for next class



# Week 7

Coming soon...
