project:
  type: website

website:
  title: "420-SN1 Notes"
  site-url: https://john-abbott-college.github.io/SN1-Notes/
  page-navigation: true
  navbar:
    logo : assets/favicons/favicon.svg
    left:
      - text: Syllabus
        menu:
        - text: "Youmna"
          href: syllabus/Youmna/Youmna.qmd
  sidebar:
    style: "docked"
    background: light
    collapse-level: 1
    contents:
    - section: Objectives
      contents:
      - topics/01_objectives/01_course_goals/01_course_goals.qmd
      - topics/01_objectives/02_probelm_solving/02_probelm_solving.qmd
      

    - section: Introduction
      contents:
      - topics/03_introduction/01_file_manipulation/01_file_manipulation.qmd
      - topics/03_introduction/02_what_is_programming/02_what_is_programming.qmd
      - topics/03_introduction/03_introduction_to_Python/03_introduction_to_Python.qmd

    - section: Getting Started
      contents:
      - href: https://www.youtube.com/watch?v=rI2Zl0ZJCzY
        text: "Install Thonny"
      - href: https://www.youtube.com/watch?v=TFbMwhkVpGM
        text: "Explore Thonny"
      - topics/02_getting_started/03_lea/03_lea.qmd 
      - topics/02_getting_started/07_thonny/thonny.qmd
    - section: Variables & Data Types
      contents:
      # - topics/04_variables/01_intro_literals/01_intro_literals.qmd
      - topics/04_variables/02_variables/02_variables.qmd
      - topics/04_variables/03_integers_floats/03_integers_floats.qmd
      - topics/04_variables/04_booleans/04_booleans.qmd
      - topics/04_variables/05_strings/05_strings.qmd
      - topics/04_variables/exercises/data_types/data_types.qmd

    - section: String Handling
      contents:
      - topics/05_string_formatting/01_f_strings/01_f_strings.qmd
      - topics/05_string_formatting/02_f_strings_formatting/02_f_strings_formatting.qmd
      - topics/05_string_formatting/03_string_ops/03_string_ops.qmd
      

    - section: Operators
      contents:
      - topics/06_operators/01_arithmetic_operators/01_arithmetic_operators.qmd
      - topics/06_operators/02_assignment_operator/02_assignment_operator.qmd
      - topics/06_operators/03_comparison_operators/03_comparison_operators.qmd
      - topics/06_operators/04_logical_operators/04_logical_operators.qmd
      - topics/06_operators/05_order_operations/05_order_operations.qmd
      - topics/06_operators/exercises/arithmetic_operators/arithmetic_operators.qmd
      - topics/06_operators/exercises/assignment_operators/assignment_operators.qmd
    
    - section: Conditions
      contents:
      - topics/07_conditionals/01_if_statements/01_if_statements.qmd
      - topics/07_conditionals/02_if_else_statements/02_if_else_statements.qmd
      - topics/07_conditionals/exercises/conditional/conditional.qmd

    - section: Loops
      contents:
      - topics/08_loops/01_for_loop/01_for_loop.qmd
      - topics/08_loops/02_while_loop/02_while_loop.qmd

    - section: Functions
      contents:
      - topics/09_functions/01_what_are_functions/01_what_are_functions.qmd
      - topics/09_functions/02_math_functions/02_math_functions.qmd
      - topics/09_functions/03_io/03_io.qmd
      - topics/09_functions/04_custom_functions/04_custom_functions.qmd
      - topics/09_functions/05_scope/05_scope.qmd
      - topics/09_functions/06_type_hinting/06_type_hinting.qmd
      - topics/09_functions/exercises/custom_functions/custom_functions.qmd
      - topics/09_functions/exercises/input_output/input_output.qmd
    
    - section: Turtle graphics
      contents:
      - topics/10_turtle/01_turtle_graphics/01_turtle_graphics.qmd
      - topics/10_turtle/02_arts_and_crafts/02_arts_and_crafts.qmd
    
    - section: Lists
      contents:
      - topics/11_lists/01_into_to_lists/01_into_to_lists.qmd
      - topics/11_lists/02_looping_over_lists/02_looping_over_lists.qmd
      - topics/11_lists/03_list_inclusion/03_list_inclusion.qmd
      - topics/11_lists/exercises/lists/lists.qmd

    - section: Data Processing
      contents:
      - topics/12_data_processing/01_reading_files/01_reading_files.qmd
      - topics/12_data_processing/02_installing_modules/02_installing_modules.qmd
      - topics/12_data_processing/03_numpy/03_numpy.qmd
      - topics/12_data_processing/04_matplotlib/04_matplotlib.qmd
    
    - section: Tooling
      contents:
      - topics/13_tooling/13_01_debugger/01_debugger.qmd

    - section: Final Exam Prep
      contents:
      - topics/14_final_exam_prep/01_study_guide/01_study_guide.qmd
      - topics/14_final_exam_prep/exercises/final_exam_f24/final_exam_f24.qmd
      - topics/14_final_exam_prep/exercises/final_exam_w25/final_exam_w25.qmd
      - topics/14_final_exam_prep/exercises/practice_midterm_f25/practice_midterm_f25.qmd
      - topics/14_final_exam_prep/exercises/upenn_exam_practice_f24/upenn_exam_practice_f24.qmd
      - topics/14_final_exam_prep/reference_sheet/reference_sheet.qmd

      
format:
  live-html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 250px   # Increase this to push the right margin/TOC further right
      gutter-width: 4rem
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    syntax-highlighting:
      light: atom-one
      dark: dracula
    code-block-bg: true
    # code-block-border-left: "#31BAE9"
    toc: true
  

  




