---
title: "🎯 Lists"
editor:
  render-on-save: true
---

## Level 1

### Some Cool Ints

Define a list of 10 integers from 1 to 10 and display the size of the list.

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    print(len(numbers))
  </code></pre>
</details>

### Some Cool Names

Define a list of 5 first names and print the list.

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    first_names = ['Sandy', 'Ian', 'Alex', 'Youmna']
  </code></pre>
</details>

### Some Cool Grades

- Prompt the user how many grades they want to enter
- Prompt the user for the grades, one at a time
- Store all the grades in a single list

<details>
  <summary>👀 Hint</summary>
  <p>how do you prompt the user with python?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    grades = []
    n: int = int( input("How many grades do you want to enter? "))

</code>
<code class="language-python">
    for i in range(n):
        grade: float = float( input(f"Enter grade for student {i+1}: "))
        grades.append(grade)

</code></pre>

</details>

### Sumthings going on here

Using the list below, calculate the total sum of each number squared

```py
nums = [1, 7, 2, -3, 5, 9]
```

<details>
  <summary>👀 Hint</summary>
  <p>total = nums₀² + nums₁² + nums₂² + nums₃² + nums₄² + nums₅²</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    total = 0
    for num in nums:
        total += num**2

</code></pre>

</details>

## Level 2

### Studying is for Squares

You're given a list of numbers:

```py
nums = [1, 2, 3, 4, 5, 6, 7]
```

Write a program that creates a new list where each number is replaced by its square, then prints the result:

```py
[1, 4, 9, 16, 25, 36, 49]
```

<details>
  <summary>👀 Hint</summary>
  <p>Use a l🔁🔁p</p>
</details>

### Reverse a List

Reverse a list without using `reverse()`. You're given the following cool list

```py
cool_list = [100, 200, 300, 400, 500]
```

Your goal is to print the reversed version:

```text
[500, 400, 300, 200, 100]
```

<details>
  <summary>👀 Hint</summary>
  <p>There are like 5 valid ways to do it, all of which use a l🔄🔄p</p>
</details>

<details>
  <summary>✅ Solution 1</summary>
  <pre><code class="language-python">
    cool_list = [100, 200, 300, 400, 500]

    start = len(cool_list) - 1
    stop = -1
    step = -1
    
    reversed_list = []
    for i in range(start, stop, step):
        item = cool_list[i]
        reversed_list.append(item)
    
    print(reversed_list)

</code></pre>
</details>

<details>
  <summary>✅ Solution 2</summary>
  <pre><code class="language-python">
    cool_list = [100, 200, 300, 400, 500]

    reversed_list = []
    for item in cool_list:
        reversed_list = [item] + reversed_list
    
    print(reversed_list)

</code></pre>
</details>

### Min / Max

Given the list: 

```py
listo = [8, 2, 15, 1, 9]
```
Write a program that finds and prints the largest and smallest numbers without using `min()` or `max()`. The expected output is:

```text
Largest number: 15
Smallest number: 1
```

<details>
  <summary>👀 Hint</summary>
  <p>How can you keep track of something over the course of a loop?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    listo = [8, 2, 15, 1, 9]

    largest = listo[0] # make a guess
    smallest = listo[0] # make a guess
    
    for n in listo:
        if n > largest:
            largest = n
        if n < smallest:
            smallest = n
    
    print(f"Largest number: {largest}")
    print(f"Smallest number: {smallest}")
</code></pre>
</details>

### Average

Givent the list of an unknown length:

```
numbers = [1,6,3,8,9,....]
```

Write a program that finds the average value without using `sum()`, `len()` nor other functions. 

<details>
  <summary>👀 Hint</summary>
  <p>Can you visit all the items and find the sum and the length?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    numbers = [1,6,3,8,9,18,27,30,12]
    count = 0
    total = 0
    for num in numbers:
        total += num
        count += 1
    print(f"The average is:: {total/count}")
</code></pre>
</details>

## Level 3

### Searching 

Given the paired lists below: 

```python
destinations= ["Cancun", "New York", "Rio", "Madrid", "Paris", "Vancouver"]
tickets = [480.0, 834.0, 954.0, 690.0, 574.0, 322.0]
```

Write a program which asks the user for a `target` destination. If it finds the destination in the list, it should print the ticket price, otherwise it should print "Destination not found". The program cannot use the method`.index()` 

**Example output 1**
```text
Where would you like to travel? Cancun
Found it! The price to go to Cancun is 480.00$
```

**Example output 2**
```text
Where would you like to travel? Cairo
Destination not found
```
<details>
  <summary>👀 Hint</summary>
  <p>You can `return` when a function is ready to exit</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    destinations= ["Cancun", "New York", "Rio", "Madrid", "Paris", "Vancouver"]
    tickets = [480.0, 834.0, 954.0, 690.0, 574.0, 322.0]
    
    target_destination = input("Where would you like to travel? ")

    if target_destination not in destinations:
      print("Destination not found")
      return  #No need to keep looking

  # search for the destination
  for dest, price in zip(destinations, tickets):
    if dest == target_destination:
      print(f"Found it! The ticket price for {dest} is {price:.2f}$ ")
      break 
	</code></pre>
</details>

### Numeric Calculus 

You are given a list of `x_values` and `y_values` without knowing the explicit formula that relates them. 
```python
x_values = [0, 0.1, 0.2, 0.3, 0.4, 0.5]
y_values = [-0.6384318904120898, 0.4680346286487408, 0.4521364981725247, 0.8607335975351307, 0.9269427310806756, 1.0982126783257407]
```


1. Write a function called `get_positives()` which takes as input a list of `xs` and a list of `ys`  and returns a list of x values where y is greater or equal to 0. 

<details>
  <summary>✅ Solution</summary>
  <pre>
  <code class="language-python">
    def get_positives(xs:list, ys:list)->list:
      positive_xs = [] 
      for x,y in zip(xs, ys):
          if y >= 0:
              positive_xs.append(x)
      return positive_xs
  </code>
  </pre>
</details>

2. Write a function called `local_minima()` which takes as input a list of `xs` and a list of `ys` and returns a list of values where y is a local minima (larger than the previous y and larger than the next y): $ y_{i-1} > y_i < y_{i+1}$ 

<details>
  <summary>👀 Hint</summary>
  <p>Use `for i in range()` to loop over the list and compare each point to the previous one and the next. Be careful of the index out of range!
</p>
</details>

<details>
<summary>✅ Solution</summary>
  <pre><code class="language-python">
  def local_minima(xs:list, ys:list)->list:
    minima = []
    for i in range(1,len(xs)-1): # to avoid index out of range
        previous = ys[i-1]
        current = ys[i]
        next_y = ys[i+1]
        # making sure current is larger than its neighbours
        if previous > current < next_y:
            minima.append(xs[i]) #save the x value
    return minima
  </code></pre>
</details>   

3. Write a function called `derive()` which takes as input a list of `xs` and a list of `ys` and finds an estimate of the derivative by calculating the slope $\frac{\Delta{y}}{\Delta{x}}$ at every point where $\Delta{x} = x_i - x_{i-1}$ and $\Delta{y} = y_i - y_{i-1}$. It should return a list of slope values for each value of x. 

<details>
  <summary>👀 Hint</summary>
  <p>Use `for i in range()` to loop over the list and compare each point to the previous one. Be careful of the index out of range!</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
  def derive(xs:list, ys:list)->list:
    slopes = []
    for i in range(1, len(xs)):
        delta_x = xs[i]-xs[i-1]
        delta_y =  ys[i] - ys[i-1]
        slope =delta_y  /delta_x
        slopes.append(slope)
    return slopes
  </code></pre>
</details>

4. Write a function `is_increasing()` which takes a list of `values` and returns `True` if the values are always increasing, otherwise return `False`.

<details>
  <summary>👀 Hint</summary>
<p>Check if a value isn't increasing compared to the previous one.</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    def is_increasing(values:list) -> bool:
      for i in range(1, len(values)):
          if values[i] <= values[i-1]: #not increasing
              return False
      return False
  </code></pre>
</details>

## Level 4

### Chaos Mode

You are giving the following chaotic list

```py
chaos = [42, 67, 'beans', True, 'butter', 64, [], False]
```

Create a new list that contains only the `True` / `False` and print it.

<details>
  <summary>👀 Hint</summary>
  <p>What must our list item be for it to be worthy of being in our new list?</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    chaos = [42, 67, "beans", True, "butter", 64, []]

    not_chaos = []
    
    for item in chaos:
        if item == True or item == False:
            not_chaos.append(item)
    
    print(not_chaos)
</code></pre>
</details>

### Flat Stanley

You're given a list of lists:

```py
list_of_lists = [[1, 2], [3, 4], [5, 6, 7]]
```

Write a program that flattens this nested list into a single list, then prints it:
```text
[1, 2, 3, 4, 5, 6, 7]
```

<details>
  <summary>👀 Hint</summary>
  <p>l🔁🔁p && .append()</p>
</details>

<details>
  <summary>✅ Solution</summary>
  <pre><code class="language-python">
    list_of_lists = [[1, 2], [3, 4], [5, 6, 7]]

    flat_stanley = []
    
    for sublist in nested_list:
      for item in sublist:
        flat_stanley.append(item)
    
    print(flat_stanley)
</code></pre>
</details>