---
title: "✍️ Variables & Data Types"
editor:
  render-on-save: true
---

::: {.callout-note .objectives icon="false" title="Learning Objectives Checklist"}

- [ ] **Recognize** the various basic data types: str, int, float and bool
- [ ] **Recognize** scientific notation for large numbers
- [ ] **Evaluate** the resulting data type of expressions that mix different data types.
- [ ] **Evaluate** a comparison between two numbers as True or False.
- [ ] **Perform** type conversions (`int()`, `float()`, `str()`) to fix type-related errors in code.
- [ ] **Distinguish** legal from illegal Python variable names.

:::

We highly recommend you work on the exercises below with pen and paper to practice for quizzes and exams.


# ✍️ **Practice**
What are the data types of the following variable:

## 1. Type Check


**a.**
```python
variable = 10
```

:::{.callout-tip title="Solution" collapse="true"}
```
'int'
```
:::

**b.**
```python
PI = 3.14
```

:::{.callout-tip title="Solution" collapse="true"}
```
'float'
```
:::

**c.**
```python
variable = 3e-5
```

:::{.callout-tip title="Solution" collapse="true"}
```
'float'
```
:::

**d.**
```python
number = "234"
```

:::{.callout-tip title="Solution" collapse="true"}
```
'str'
```
:::

**e.**

```python
value = "2"
value2 = int(value)
print(type(value2))
```

:::{.callout-tip title="Solution" collapse="true"}
`value`→ `str`
`value2` → `int`
:::

**f.**

```python
grade = 24
total = 25
ratio = grade / total
```

:::{.callout-tip title="Solution" collapse="true"}
`grade` → `int`
`total` → `int`
`ratio` → `float`
:::

**g.**
```python
num_classrooms = 5
pcs_per_classroom = 22
total_pcs = num_classrooms * pcs_per_classroom

```

:::{.callout-tip title="Solution" collapse="true"}
'int'
:::

**h.**
```python
var1 = 1
var2 = 2
var3 = "3"
var4 = var1 + var2 + var3
```

:::{.callout-tip title="Solution" collapse="true"}
var1 → `int`
var2 → `int`
var3 → `str`
var4 → Error, cannot use + on numeric data types with str.
:::

**i.**
```python
is_freezing = False
```

:::{.callout-tip title="Solution" collapse="true"}
'bool'
:::

**j.**

```python
age = 25
is_legal_age = (age >= 18)

```

:::{.callout-tip title="Solution" collapse="true"}

`int`
'bool'
:::

**k .**

```python
cars_count = 3
has_cars = bool(cars_count)
```

:::{.callout-tip title="Solution" collapse="true"}
`int`
`bool`
:::

## 2. Illegal Variable Names
Which of the following variable names are **illegal**?

- `TRUE`
- `True`
- `true`

:::{.callout-tip title="Solution" collapse="true"}
`True` — reserved keyword for the Boolean type.
:::

# 🧩 **Problem Solving**

## 1. Sum of Mismatched Types
Fix the mistakes in the program below so that `sum_val` gets the value `6`.

```{pyodide}
num1 = 2
num2 = "4"

# Intended result: sum_val gets the value 6.
sum_val = num1 + num2
```

<details>
  <summary>👀 Hint</summary>
  <p>Double check the data types of the inputs!</p>
</details>

:::{.callout-tip title="Solution" collapse="true"}
```{python}
# Solution #1
num1 = 2
num2 = 4
sum_val = num1 + num2

# Solution #2
# num1 = 2
# num2 = "4"
# sum_val = num1 + int(num2)

# Are there any other solutions you can come up with?
print(sum_val)
```
:::

## 2. Average Grades
Fix the calculation error in the program below, which is supposed to calculate a simple average of two grades.

```{pyodide}
grade1 = 25
grade2 = 26

average = int(grade1+grade2/2)
print(average)
```

<details>
  <summary>👀 Hint</summary>
  <p>There is more than one issue in the code above. How are averages calculated? And what type of data should they be?</p>
</details>

:::{.callout-tip title="Solution" collapse="true"}
```{python}
grade1 = 25
grade2 = 26
average = (grade1 + grade2) / 2
print(average)
```
:::


# 3. Gravitational potential energy
Calculate the gravitational potential energy of an object using the following formula, where $m$ is the mass of the object, $g$ is the acceleration of gravity which is 9.81 $m/s^2$, $h$ is the height at which the object is located. Assume that the object has a mass of 18Kg and is held at a height of 200 m. Ensure that you are following the naming convention mentioned earlier.

$$

E_p = m \times g \times h

$$

<details>
  <summary>👀 Hint</summary>
  <p>Python variable names should be meaningful!</p>
</details>

:::{.callout-tip icon="false" title="Solution" collapse="true"}

```python

GRAVITATION_ACC = 9.81

mass = 18
height = 200
energy = GRAVITATION_ACC * mass * height

```
:::