---
title: "Arithmetic operators"
editor:
  render-on-save: true
---
::: {.callout-note .objectives icon="false" title="☆ Learning Objectives "}

- **Apply** the addition (+), subtraction (-), multiplication (*), and division (/) operators in Python expressions.
- **Apply** the exponentiation (**) operator to calculate powers.
- **Apply** the modulo (%) and floor division (//) operators to solve programming problems.
- **Evaluate** arithmetic expressions on variables of the different basic data types: `int`, `float`, `string`, `bool`
- **Evaluate** Python expressions by applying the correct priority of operations.

:::

**Operators**: Similarly to mathematics, the `+`, `-`, `*`, `/` are operators used to perform arithmetic operations on numbers. In Python, these operators can also be used on other data types but with caution. Complications may arise if you combine literals of different types. For example, `2 + "4"` will lead to an error and `5 + True` won't crash but isn't necessarily correct.


# Combining data types

To use arithmetic operators correctly, you should first be aware of the different data types and their behaviour when used with arithemtic operators.

## Strings 
- Strings can be combined (or concatenated) to other strings using the `+` operator
- Strings should **never** be combined to other types or else the program crashes.

:::{.callout-note title="Multiplying a string" collapse="true"}
There is only one exception. Python allows a `string` to be "multiplied"  n times (`int`) which creates a longer string repeating the original string. Eg:
```{python}
base = "Hi"
print(base*4)
```
:::

## Numbers
Arithmetic operations are deisigned for integers and floats. These types can also be safely used together. But, since integers have no fractional part, they will be automatically converted to floats by Python when combined to floats:
```{python}
print( 3.5 + 5)
```
- The result is always a `float`


You can also explicitly convert `float` to `int` if this is intended outcome.

```{python}
print(int(3.5) + 5)
```

:::{.callout-important title="Loss of precision"}
This will truncate the decimal part of the `float` number, the resulting `int` is `3`. Therefore, you must be careful when performing those conversion because this might result in loosing precision or loosing information. We say that `float`s are **wider** range than `int`or `int` are **narrower** than floats.
:::

## Booleans

Although extremely rare, arithmetic operations with the `bool` type are possible in Python.

If you perform an addition, such as: `True + True`, Python will convert the `bool` into integers `1` (or `0` for `False`), and still performs the operation (`1+1 = 2`). If it's a more complex operation, for example `False / True`, the values will be converted to `float`, therefore the result will be `0.0 / 1.0 = 0.0`. Conceptually, this makes no sense, therefore we'll tend to avoid those situations. 



In summary, when performing arithmetic operation, ensure all the variables are in the correct type, don't mix strings with numeric variables, and avoid using booleans. 

# Table of operators

Here is an extensive table with all opertors applied to `string`, `int` and `float`:

 Operator | Name | `string` with `string` | `int` with `int` | `float` with `float` | `int` with `float` |
|:--------:|------|------------------------|-----------------:|---------------------:|-------------------:|
| `+`  | Addition       | `"H" + "i"` → `"Hi"` | `3 + 2` → `5` | `3.2 + 2.5` → `5.7` | `3 + 2.0` → `5.0` |
| `-`  | Subtraction    | Error ❌ | `3 - 2` → `1` | `3.2 - 2.5` → `0.7` | `3 - 2.0` → `1.0` |
| `*`  | Multiplication | Error ❌ | `3 * 2` → `6` | `3.5 * 2.0` → `7.0` | `3 * 2.0` → `6.0` |
| `/`  | Division       | Error ❌ | `3 / 2` → `1.5` | `3.0 / 2.0` → `1.5` | `3 / 2.0` → `1.5` |
| `//` | Floor Division | Error ❌ | `3 // 2` → `1` | `4.0 // 3.0` → `1.0` | `4 // 2.0` → `2.0` |
| `%`  | Modulo         | Error ❌ | `10 % 7` → `3` | `7.0 % 5.0` → `2.0` | `7 % 5.0` → `2.0` |
| `**` | Power          | Error ❌ | `4 ** 2` → `16` | `4.0 ** 2.0` → `16.0` | `4 ** 2.0` → `16.0` |

## Modulus `%`


The **modulus** operation returns the remainder of a long division (e.g. `7 % 5 = 2`). It's most commonly used on integers and rarely used on floats. If is an easy way to verify if a number is divisible by another number (remainder is 0).


:::{.callout-note title="LONG DIVISION"}
- To grasp this operator, it's essential to recall what a long division remainder is. Consider the following division:
  $$
  7/5 = 1.4  = 1 + 2/5
  $$

  - Quotient: 1
  - Remainder: 2
:::


- If performing this operation with two `int`, the result will be an `int`

::: {.callout-note collapse="true" title="Modulo on other types"}

- If performing this operation with two `float`, the result will be a `float` (e.g.: `7.0 % 5.0 = 2.0`)

- If performing this operation with an `int` and a `float`, the int is automatically converted into the wider type `float` and the result is a `float`.

- This operator doesn't apply to string literals and will cause an error if used on strings.
:::

### Checking if a number is even/odd

This operator is useful to determine if a number is odd or even. If it even, the remainder of a division by `2` would be `0`. Otherwise, if the number is odd, the remainder would be `1`:

```{python}
print("Odd numbers")

print(1 % 2)
print(3 % 2)
print(5 % 2)
print(51 % 2)

print("Even numbers")

print(0 % 2)
print(2 % 2)
print(4 % 2)
print(50 % 2)
```

## Floor division `//`

Divides the first operand by the second and rounds the result **down** to the nearest whole number. It'll compute the division, but then discard the fractional part and the result is always an **integer**.

- It's useful when dealing with "countable" elements such as count of people, count of objects, number of pixel. These enties can be divided further, the result of the operation must be an integer.

- You can also replace the use of the `//` by performing a normal division with `/`, then converting the result into an `int`: `x // y` is the same as `int(x/y)`

```{python}

a = 4
b = 3

result = a//b
```

Is the 

::: {.callout-note collapse="true" title="Floor Division on other types"}
- If two `int` are used in this operation, the result is and `int`
- If any of the number is a `float`, the result will be a `float` and any integer will automatically be converted to the wider type `float`.
- This operator doesn't apply to string literals and will cause an error if used on strings.
:::

✍️**Challenge 1**: Manually execute the operations of the program below and write the expected result. Check your answers by running the code.


```{pyodide}
w = 2
x = 10.0
y = 7

a = w + y
b = y - w
c = 10 % 7
d = y // w
e = y ** w
f = w * x
g = y / x
print(a,b,c,d,e,f,g)
```

✍️**Challenge 2**: Manually execute the operations below and write the expected result. Check your answers by running the code.


```{pyodide}
a = 9
b = 4
c = 5
x = a % b
y = a // c
print(x, y)
```


```{pyodide}
a = 5.5
b = 5

x = a % b
y = a // b
print(x, y)
```

```{pyodide}
a = -7
b = -4
x = a % b
y = (a + b) // b
print(x, y)
```

✍️**Challenge 3**: Write a short program which given a `budget`, calculates how many t-shirts they can purchase. Assume each t-shirt costs $15, including tax.

```{pyodide}
budget = 115.0

# Complete this...

```

:::{.callout-tip collapse="true" title="Solution"}
```{python}
budget = 115.0
cost_one = 15.0

num_t_shirts = budget//cost_one

```
:::

🏆✍️**Expert Challenge**: Write a short program to help the school administration calculate the number of sections per course given a certain number of registered students. Most groups should have an even number of students, with at least 18 students per classroom and a maximum of 32 students. The administration tries to minimize the number of groups and balances the number of students per classroom.

> Note: There are many possible answers for this problem, but some answers are more optimal than others. You are allowed to use any arithmetic operators and simple if statements.

:::{.callout-tip collapse="true" title="Solution"}

Find it [here](https://app.codeboot.org/5.0.0/?init=.oYXJpdGhtZXRpY3MxLnB5~XQAAgABzAAAAAAAAAAA7iAOiEWEBkg99P3WsHCwTzyEnkel2CBOuLrjllUppjR2CUAq-gAuD7LU2oyanmA9U_RpSi-drNpr416lu9L-NrvGsbtQ5a-GEWkgA0kTkSGfwDTPluIsbrwON_vHxgA==.oYXJpdGhtZXRpY3MyLnB5~XQAAgAAyAAAAAAAAAAAwiAOiEahbOGuxQe1CZvIjyRYu5mub1I1Va1AIIODnRLN-GxtFSkmZFiGNPbP__7xKAAA=.oYXJpdGhtZXRpY3MzLnB5~XQAAgAAvAAAAAAAAAAAwiAOiEYBKyZe2I4QdWm7UXFjOvyviV84ZJSWiNp-9cEcuUekImN8jtfnmf3_4HMgA.oYXJpdGhtZXRpY3M0LnB5~XQAAgAA0AAAAAAAAAAAwiAOiES9Ps37Inw0qfG9M7-T-i9pIlseMPdretZIdGs5iE_XRmjDhfUT9FqrYzaHB_-xOgAA=.oc3R1ZGVudHNfcGVyX2NsYXNzcm9vbS5weQ==~XQAAgAC3AwAAAAAAAAARZ_6IyAHcsKA_gk8ErULb3y_0mEvwAQUvSH3Io5HuKO0lev5qHJtmUud-z0lOQyR4V5aTBthfzVxSylCfQyxTnKr23mg9xiuAJ0bEUJFpJbHv9MIsq-lktXXhTmnhrPY6MrWQI6HjUbh30gSnRHGTsz37WSSDvMx1STuZY19MoJ5zas8J9aUwZZzhZzVPp0j7w8mE_glYQPRLRqAcS3TVLgXqBwZBT9RnJgELR1Csakc8EMNeN37ReX5_TNtZQz_MSWXwMHId0TCjFkyOKeVjXdprzJ64S77CweI2YnN1TBgBuabcZHePq4pHbV3Yf1eyhhfCFq26Jq02dWDwuaHzoKazt0S29qpWLGhkL7Za9WsWtFENo76gcpJM9hsqdZNKXriIyFZRbsgAEE9M9bF055daGQcb-kjpvq5aFf-IU01recFkZJ24NSd6ddZConWiEAWqOB_u-_x75A==.fc3R1ZGVudHNfcGVyX2NsYXNzcm9vbV8yLnB5~XQAAgABVCAAAAAAAAAARaAQIZvNx2aPvSLSjLYQfdOpuOXia6VgdWdqdP6BlGcP6R0JD_HLKEarDGKRtsSjY-1tTLZ3jzLL25cCmEralncL5cLPelfiJci5_OwHVAyPm3pSgwDcDWZ2BLHVn5SCjSl2YqdnbXwyWS2SuBPseRjH9DAqI9TSAj8dVdn-VtFKoLjXU5S4bOxQkmUEB8XEmzojR4F_HEPOBpR_FJ-ZLafJ_mupI_JeDgBQQOHjhASaKSDA9C_6V7P1XBQ5dbCY_qjHx5yWBX1rbEu-5FTBkBDL3PAOlmGUUVZyc14fHlIDhg5NiGr8G_41npD0gwOwaU08BI3L7lYe6PL_gTeGJ46BwvadLTALvFHAeuhpZXEggwmZ7iKzO7dZdTMaO-y5-JgHuShKlO4S9lZQxb3jP3lsp9Xf_Lf1WIM54m5OGOTiz26pKH20lZa2GjNwZCGSiZjUhLkhpaFGS4VB5JVVvx_331JOEI3pY_M57WO2l7_Uz-TCbpvVwKTff4aVvzuRvS_2DTtIbYjBIlME25wmfBK8s-Q7ouKdptwBpAPkeBi3sYRyGtc5BLAvE7-usjbdDk6Nk56qKKQjBZyk_yAcoSKzcPfs3qiyzmWELx28irP0FvgpHU3UhAyygjjwUoPKEs74z7FRJHBIv-NuImjUqS0JTKwpWHkM5Y1ttJ7ar_QD7tzUY3d4xWmWxH5U3VVYXW8-IJsxKGkqcQBTzn1ZXlpbLZpiu0ZnZdSCcIuA5Ftb01-r_HOaCAVENHHu83UZfUDZT5Vrn-61kHmP1DDucS-CX9iEzaJl0IXYEWhx0qY0e5x8i9xAagcYGR5kigJZyJv_78gdHuZLwxgdhdGaRz4tXUbvnvyWPQyQHwf-ZTm2Yf1FUs1z-ekrxiRHvU6GV9tUmfCw5EFlwNuRr2ijv09XybRM_rZf75_8AFIzklxU6EN84tA25VLH_8MnCXA==.~lang=py-novice.~showLineNumbers=true.e)
:::